version: '2'
services:
    sputnik-app:
        image: sputnik
        external_links:
            - sputnik-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=sputnik
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sputnik-mongodb:
        extends:
            file: mongodb.yml
            service: sputnik-mongodb
