version: '2'
services:
    sputnik-mongodb:
        container_name: sputnik-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/sputnik/mongodb/:/data/db/
